package blocktext_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/BeppeTemp/cartographer/internal/blocktext"
)

const (
	begin = "# begin"
	end   = "# end"
)

func TestWrite_CreatesFileIfAbsent(t *testing.T) {
	path := filepath.Join(t.TempDir(), "sub", "cfg.toml")
	if err := blocktext.Write(path, begin, end, "body\n"); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "# begin\nbody\n# end\n"
	if string(data) != want {
		t.Errorf("got %q, want %q", data, want)
	}
}

func TestWrite_ReplacesExistingBlock_PreservesRest(t *testing.T) {
	path := filepath.Join(t.TempDir(), "cfg.toml")
	initial := "# user comment\nkey = \"value\"\n\n# begin\nold body\n# end\n\n[other]\nx = 1\n"
	if err := os.WriteFile(path, []byte(initial), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := blocktext.Write(path, begin, end, "new body"); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "# user comment\nkey = \"value\"\n\n# begin\nnew body\n# end\n\n[other]\nx = 1\n"
	if string(data) != want {
		t.Errorf("got %q, want %q", data, want)
	}
}

func TestWrite_AppendsIfMarkersAbsent(t *testing.T) {
	path := filepath.Join(t.TempDir(), "cfg.toml")
	initial := "key = \"value\"\n"
	if err := os.WriteFile(path, []byte(initial), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := blocktext.Write(path, begin, end, "body"); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "key = \"value\"\n\n# begin\nbody\n# end\n"
	if string(data) != want {
		t.Errorf("got %q, want %q", data, want)
	}
}

func TestWrite_Idempotent(t *testing.T) {
	path := filepath.Join(t.TempDir(), "cfg.toml")
	for i := 0; i < 3; i++ {
		if err := blocktext.Write(path, begin, end, "body"); err != nil {
			t.Fatal(err)
		}
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "# begin\nbody\n# end\n"
	if string(data) != want {
		t.Errorf("got %q, want %q", data, want)
	}
}

func TestRemove_StripsBlock_KeepsRest(t *testing.T) {
	path := filepath.Join(t.TempDir(), "cfg.toml")
	initial := "key = \"value\"\n\n# begin\nbody\n# end\n"
	if err := os.WriteFile(path, []byte(initial), 0o644); err != nil {
		t.Fatal(err)
	}
	removed, err := blocktext.Remove(path, begin, end, false)
	if err != nil {
		t.Fatal(err)
	}
	if !removed {
		t.Error("expected removed = true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	// The blank line that separated the key from the block was part of the
	// file, not generated by the block itself — Remove only strips the marker
	// span (markers + one trailing newline), so it's preserved verbatim.
	if string(data) != "key = \"value\"\n\n" {
		t.Errorf("got %q", data)
	}
}

func TestRemove_DeletesFileIfLeftEmpty(t *testing.T) {
	path := filepath.Join(t.TempDir(), "cfg.toml")
	initial := "# begin\nbody\n# end\n"
	if err := os.WriteFile(path, []byte(initial), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := blocktext.Remove(path, begin, end, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Error("expected file to be removed once left empty")
	}
}

func TestRemove_NoFile_NoOp(t *testing.T) {
	path := filepath.Join(t.TempDir(), "missing.toml")
	removed, err := blocktext.Remove(path, begin, end, false)
	if err != nil || removed {
		t.Errorf("removed=%v err=%v, want false/nil", removed, err)
	}
}

func TestRemove_NoMarkers_NoOp(t *testing.T) {
	path := filepath.Join(t.TempDir(), "cfg.toml")
	if err := os.WriteFile(path, []byte("key = 1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	removed, err := blocktext.Remove(path, begin, end, false)
	if err != nil || removed {
		t.Errorf("removed=%v err=%v, want false/nil", removed, err)
	}
	data, _ := os.ReadFile(path)
	if string(data) != "key = 1\n" {
		t.Error("file must be untouched")
	}
}

func TestRemove_DryRun_DoesNotWrite(t *testing.T) {
	path := filepath.Join(t.TempDir(), "cfg.toml")
	initial := "key = 1\n\n# begin\nbody\n# end\n"
	if err := os.WriteFile(path, []byte(initial), 0o644); err != nil {
		t.Fatal(err)
	}
	removed, err := blocktext.Remove(path, begin, end, true)
	if err != nil {
		t.Fatal(err)
	}
	if !removed {
		t.Error("dry-run should still report removed = true (what would happen)")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != initial {
		t.Error("dry-run must not modify the file")
	}
}

func TestWrite_ReplacesLegacyLocalizedBeginMarker(t *testing.T) {
	// Older versions wrote the begin marker with a different human-readable
	// tail after the em dash (e.g. in Italian). Recognition goes through the
	// stable prefix: the block must be replaced, not duplicated.
	path := filepath.Join(t.TempDir(), "cfg.toml")
	legacy := "# begin — vecchio testo localizzato\nold body\n# end\n"
	if err := os.WriteFile(path, []byte(legacy), 0o644); err != nil {
		t.Fatal(err)
	}
	newBegin := "# begin — new english tail"
	if err := blocktext.Write(path, newBegin, end, "new body"); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := newBegin + "\nnew body\n# end\n"
	if string(data) != want {
		t.Errorf("got %q, want %q", data, want)
	}
	if strings.Count(string(data), "# begin") != 1 {
		t.Errorf("begin marker duplicated:\n%s", data)
	}
}
