//go:build !windows

package provisioning

// The POSIX half of the bootstrap script (D60). The name and the body are
// build-tagged rather than switched on runtime.GOOS (docs/conventions.md
// §Dependencies): the script is generated for the machine it will run on, and
// there is no case in which a client materializes the other platform's script.
//
// bootstrapContentHash (bootstrap.go) is computed from these constants at init,
// so it becomes platform-dependent by construction. Nothing may pin its literal
// value — a test that needs it must derive it the same way.

// bootstrapScriptName is the generated script's file name inside the hook's
// destination directory (destDir("hook", BootstrapHookName, provider)).
const bootstrapScriptName = "bootstrap.sh"

// bootstrapScriptContent is the deterministic body of the generated bootstrap
// script — identical for every provider. Silent (all output discarded) and
// always exit 0: a sync failure (e.g. server down) must never break session
// startup. `cartographer sync` itself already runs over an HTTP client with a
// bounded timeout (internal/client, 30s) — no extra timeout needed here.
const bootstrapScriptContent = `#!/bin/sh
# cartographer-bootstrap — generated by Cartographer (WP4/D60), do not edit.
command -v cartographer >/dev/null 2>&1 || exit 0
cartographer sync --auto-trust >/dev/null 2>&1 || true
`
