// bootstrap.go (D60) — the "cartographer-bootstrap" hook: a synthetic artifact,
// generated entirely by the client (not by the server/KB manifest), that at
// session start silently runs `cartographer sync --auto-trust` so the LLM agent
// always starts aligned with the server, without the user having to run `sync`
// by hand. See docs/decisions/sync-provisioning.md D60, docs/sync.md §Layer 1.
//
// EnsureBootstrapHook reuses exactly the D57 (Claude settings.json), D58 (Codex
// config.toml) and D59 (OpenCode plugin) registration primitives used by Apply
// for KB hooks — same hook.json schema + script in a dedicated directory, same
// idempotence. The only difference is that here the directory is not populated
// by reading files from the KB (copyArtifactFiles) but by writing the two
// generated files directly (bootstrapHookJSON, bootstrapScriptContent).
package provisioning

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/BeppeTemp/cartographer/internal/configurator"
)

// BootstrapHookName is the reserved hook name for the client-generated bootstrap
// hook (D60). A KB that defines a hook with this exact name collides with it:
// Apply ignores that KB artifact with a warning (see the reserved-name check in
// Apply) rather than letting it shadow the files EnsureBootstrapHook manages.
const BootstrapHookName = "cartographer-bootstrap"

// bootstrapScriptName is the generated script's file name inside the hook's
// destination directory (destDir("hook", BootstrapHookName, provider)).
const bootstrapScriptName = "bootstrap.sh"

// bootstrapScriptContent is the deterministic body of the generated bootstrap
// script — identical for every provider. Silent (all output discarded) and
// always exit 0: a sync failure (e.g. server down) must never break session
// startup. `cartographer sync` itself already runs over an HTTP client with a
// bounded timeout (internal/client, 30s) — no extra timeout needed here.
const bootstrapScriptContent = `#!/bin/sh
# cartographer-bootstrap — generated by Cartographer (WP4/D60), do not edit.
command -v cartographer >/dev/null 2>&1 || exit 0
cartographer sync --auto-trust >/dev/null 2>&1 || true
`

// bootstrapHookJSON renders the hook.json content the bootstrap hook's directory
// is materialized with — same shape KB hooks use (readHookSpec/hookSpec), so
// registerHookSettings/registerHookConfigTOML/registerOpenCodePlugin work on it
// completely unmodified. SessionStart has no matcher semantics in any of the three
// engines, so Matcher is left empty.
func bootstrapHookJSON() []byte {
	data, err := json.Marshal(hookSpec{Event: "SessionStart", Command: "./" + bootstrapScriptName})
	if err != nil {
		// hookSpec is a plain struct of strings: Marshal cannot fail on it.
		panic(err)
	}
	return data
}

// bootstrapContentHash is a fixed content hash for the bootstrap hook's
// ManagedFile entries. It is never compared by ComputeDiff (the reserved name is
// excluded from diffing entirely, see ComputeDiff/Apply) — it only exists so the
// ManagedFile has a well-formed, non-empty ContentHash like every other kind.
var bootstrapContentHash = contentHashBytes(append(bootstrapHookJSON(), []byte(bootstrapScriptContent)...))

// EnsureBootstrapHook materializes and registers the cartographer-bootstrap hook
// (D60) for provider under baseDir, and returns lock with its ManagedFile entries
// refreshed (any previous bootstrap entries replaced — idempotent, safe to call on
// every `connect`/`sync`). Independent of any server manifest: this is what lets
// the hook install even when the server is unreachable at connect time, and what
// lets a later session self-heal once it comes back.
//
// kiro has no hook mechanism (destDir("hook", _, kiro) == ""): no-op, lock
// returned unchanged.
//
// dryRun performs no I/O and simulates the resulting paths (mirrors Apply's own
// DryRun contract) — used by `connect --dry-run`/`sync --dry-run`.
//
// The returned Lock is meant to be persisted by the caller (merged into the v2
// LockFile) — from then on PruneManaged/`cartographer disconnect` remove the
// bootstrap hook's files and provider-native registration exactly like any
// KB-provided hook, no new removal code needed (see ComputeDiff/Apply for how the
// reserved name is protected from being flagged as a server-driven orphan in the
// meantime).
func EnsureBootstrapHook(baseDir string, provider configurator.Provider, lock Lock, dryRun bool) (Lock, error) {
	destRel := destDir("hook", BootstrapHookName, provider)
	if destRel == "" {
		return lock, nil
	}

	var relPaths []string
	if dryRun {
		relPaths = []string{
			filepath.Join(destRel, "hook.json"),
			filepath.Join(destRel, bootstrapScriptName),
		}
		if pluginRel := HookPluginRelPath(provider, BootstrapHookName); pluginRel != "" {
			relPaths = append(relPaths, pluginRel)
		}
	} else {
		fullDestDir := filepath.Join(baseDir, destRel)
		if err := mkdirAllNoFollow(baseDir, fullDestDir, 0o755); err != nil {
			return Lock{}, fmt.Errorf("provisioning: mkdir %s: %w", fullDestDir, err)
		}
		hookJSONPath := filepath.Join(fullDestDir, "hook.json")
		if err := writeFileNoFollow(hookJSONPath, bootstrapHookJSON(), 0o644); err != nil {
			return Lock{}, fmt.Errorf("provisioning: write %s: %w", hookJSONPath, err)
		}
		scriptPath := filepath.Join(fullDestDir, bootstrapScriptName)
		if err := writeFileNoFollow(scriptPath, []byte(bootstrapScriptContent), 0o755); err != nil {
			return Lock{}, fmt.Errorf("provisioning: write %s: %w", scriptPath, err)
		}
		// WriteFile applies the mode only on creation: a pre-existing
		// bootstrap.sh (e.g. written 0600 by an earlier version) would stay
		// non-executable → Permission denied on every SessionStart.
		if err := os.Chmod(scriptPath, 0o755); err != nil {
			return Lock{}, fmt.Errorf("provisioning: chmod %s: %w", scriptPath, err)
		}
		relPaths = []string{
			filepath.Join(destRel, "hook.json"),
			filepath.Join(destRel, bootstrapScriptName),
		}

		// Register in the provider's native mechanism, reusing exactly the
		// D57/D58/D59 primitives — the very same code Apply uses for KB
		// hooks, with the hook.json just written above acting as the bridge.
		if mechanism, ok := hookMechanisms[provider]; ok {
			pluginRel, warning, err := mechanism.register(baseDir, BootstrapHookName, fullDestDir)
			if err != nil {
				return Lock{}, err
			}
			if warning != "" && mechanism.warningBlocksBootstrap {
				return Lock{}, fmt.Errorf("provisioning: bootstrap hook: %s", warning)
			}
			if pluginRel != "" {
				relPaths = append(relPaths, pluginRel)
			}
		}
	}

	// The hash of what is on disk (D138), so on-disk verification (D139) and
	// `cartographer doctor` (D143) cover the bootstrap hook like any other
	// managed artifact instead of reporting it as unverifiable forever. It is
	// computed from the same constants written above, never read back, and a
	// dry run records nothing: there is nothing on disk to describe.
	materializedHash := ""
	if !dryRun {
		materializedHash = hashArtifactFiles([]ArtifactFile{
			{Path: "hook.json", Content: bootstrapHookJSON()},
			{Path: bootstrapScriptName, Content: []byte(bootstrapScriptContent), Executable: true},
		})
	}

	managed := make([]ManagedFile, 0, len(relPaths))
	for _, rp := range relPaths {
		managed = append(managed, ManagedFile{
			Kind:             "hook",
			Name:             BootstrapHookName,
			Path:             rp,
			ContentHash:      bootstrapContentHash,
			MaterializedHash: materializedHash,
		})
	}

	newManaged := make([]ManagedFile, 0, len(lock.Managed)+len(managed))
	for _, mf := range lock.Managed {
		if mf.Kind == "hook" && mf.Name == BootstrapHookName {
			continue
		}
		newManaged = append(newManaged, mf)
	}
	lock.Managed = append(newManaged, managed...)
	return lock, nil
}

// hookMechanism describes how a provider registers a materialized hook in its
// own configuration (D137): claude patches settings.json (D57), codex a
// marker-delimited block in config.toml (D58), opencode generates a plugin JS
// file that *is* the registration (D59). A provider absent from
// hookMechanisms has no hook mechanism at all — kiro, whose "hook" cell in
// destinationMatrix is unsupported, so nothing reaches here for it.
type hookMechanism struct {
	// settingsFile is the provider-native file the registration is written
	// into, relative to the base dir. Empty when the registration is a
	// generated artifact of its own (opencode).
	settingsFile []string
	// pluginPath derives that generated artifact's path, relative to the base
	// dir. Nil when the provider has none.
	pluginPath func(name string) string
	// warningBlocksBootstrap makes a non-fatal warning fatal for the
	// bootstrap hook specifically. True only for opencode: its warning means
	// the hook's event has no OpenCode equivalent, and SessionStart is always
	// mapped (openCodeHookEvents) — a warning there would mean the mapping
	// regressed, and silently leaving the bootstrap hook unregistered is
	// worse than failing. Codex's warning is a D99 repair notice, informational.
	warningBlocksBootstrap bool
	// register performs the registration, returning the relative path of any
	// generated artifact (so it is tracked as a managed file) plus any
	// non-fatal warning for the caller to surface.
	register func(baseDir, name, fullDestDir string) (relPath, warning string, err error)
}

var hookMechanisms = map[configurator.Provider]hookMechanism{
	configurator.ProviderClaudeCode: {
		settingsFile: []string{".claude", "settings.json"},
		register: func(baseDir, name, fullDestDir string) (string, string, error) {
			if err := registerHookSettings(baseDir, name, fullDestDir); err != nil {
				return "", "", fmt.Errorf("provisioning: register hook %s in settings.json: %w", name, err)
			}
			return "", "", nil
		},
	},
	configurator.ProviderCodex: {
		settingsFile: []string{".codex", "config.toml"},
		register: func(baseDir, name, fullDestDir string) (string, string, error) {
			warning, err := registerHookConfigTOML(baseDir, name, fullDestDir)
			if err != nil {
				return "", "", fmt.Errorf("provisioning: register hook %s in config.toml: %w", name, err)
			}
			return "", warning, nil
		},
	},
	configurator.ProviderOpenCode: {
		pluginPath:             openCodePluginRelPath,
		warningBlocksBootstrap: true,
		register: func(baseDir, name, fullDestDir string) (string, string, error) {
			// Unlike claude/codex (patching an existing shared file), here the
			// registration produces a NEW dedicated file (the generated
			// plugin, D59) — the caller appends it to the managed files so it
			// is pruned like any other, not left as a silent side effect.
			//
			// openCodePluginRelPath prefixes with "cartographer-"
			// unconditionally (same helper every KB hook uses) — for
			// BootstrapHookName ("cartographer-bootstrap") that yields a
			// double-prefixed file name. Documented, deliberate (D60):
			// reusing the shared helper verbatim keeps registration and
			// removal (removeOpenCodePlugin, driven by PruneManaged/mf.Name)
			// on the exact same path-derivation logic.
			pluginRel, warning, err := registerOpenCodePlugin(baseDir, name, fullDestDir)
			if err != nil {
				return "", "", fmt.Errorf("provisioning: register hook %s as opencode plugin: %w", name, err)
			}
			return pluginRel, warning, nil
		},
	},
}

// SupportsSessionHook reports whether the bootstrap hook (D60) can run at
// session start for this provider: it needs both a destination for the hook's
// files and a native registration mechanism. A provider without one syncs
// only on demand, or on the scheduled trigger (D140,
// `cartographer service sync-timer install`).
func SupportsSessionHook(provider configurator.Provider) bool {
	if destDir("hook", BootstrapHookName, provider) == "" {
		return false
	}
	_, ok := hookMechanisms[provider]
	return ok
}

// HookRegistrationFile returns the provider-native file a hook registration is
// written into, relative to the client base dir, or "" when the provider
// registers through a generated artifact instead (or has no hook mechanism).
// Exported for the client's own output: `cartographer sync` reports where a
// hook was registered.
func HookRegistrationFile(provider configurator.Provider) string {
	m, ok := hookMechanisms[provider]
	if !ok || len(m.settingsFile) == 0 {
		return ""
	}
	return filepath.Join(m.settingsFile...)
}

// HookPluginRelPath returns the path, relative to the client base dir, of the
// dedicated registration artifact this provider generates for hook name — or
// "" when it registers into a shared settings file instead.
func HookPluginRelPath(provider configurator.Provider, name string) string {
	m, ok := hookMechanisms[provider]
	if !ok || m.pluginPath == nil {
		return ""
	}
	return m.pluginPath(name)
}
