// bootstrap.go (D60) — the "cartographer-bootstrap" hook: a synthetic artifact,
// generated entirely by the client (not by the server/KB manifest), that at
// session start silently runs `cartographer sync --auto-trust` so the LLM agent
// always starts aligned with the server, without the user having to run `sync`
// by hand. See docs/decisions.md D60, docs/sync.md §Layer 1.
//
// EnsureBootstrapHook reuses exactly the D57 (Claude settings.json), D58 (Codex
// config.toml) and D59 (OpenCode plugin) registration primitives used by Apply
// for KB hooks — same hook.json schema + script in a dedicated directory, same
// idempotence. The only difference is that here the directory is not populated
// by reading files from the KB (copyArtifactFiles) but by writing the two
// generated files directly (bootstrapHookJSON, bootstrapScriptContent).
package provisioning

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/BeppeTemp/cartographer/internal/configurator"
)

// BootstrapHookName is the reserved hook name for the client-generated bootstrap
// hook (D60). A KB that defines a hook with this exact name collides with it:
// Apply ignores that KB artifact with a warning (see the reserved-name check in
// Apply) rather than letting it shadow the files EnsureBootstrapHook manages.
const BootstrapHookName = "cartographer-bootstrap"

// bootstrapScriptName is the generated script's file name inside the hook's
// destination directory (destDir("hook", BootstrapHookName, provider)).
const bootstrapScriptName = "bootstrap.sh"

// bootstrapScriptContent is the deterministic body of the generated bootstrap
// script — identical for every provider. Silent (all output discarded) and
// always exit 0: a sync failure (e.g. server down) must never break session
// startup. `cartographer sync` itself already runs over an HTTP client with a
// bounded timeout (internal/client, 30s) — no extra timeout needed here.
const bootstrapScriptContent = `#!/bin/sh
# cartographer-bootstrap — generated by Cartographer (WP4/D60), do not edit.
command -v cartographer >/dev/null 2>&1 || exit 0
cartographer sync --auto-trust >/dev/null 2>&1 || true
`

// bootstrapHookJSON renders the hook.json content the bootstrap hook's directory
// is materialized with — same shape KB hooks use (readHookSpec/hookSpec), so
// registerHookSettings/registerHookConfigTOML/registerOpenCodePlugin work on it
// completely unmodified. SessionStart has no matcher semantics in any of the three
// engines, so Matcher is left empty.
func bootstrapHookJSON() []byte {
	data, err := json.Marshal(hookSpec{Event: "SessionStart", Command: "./" + bootstrapScriptName})
	if err != nil {
		// hookSpec is a plain struct of strings: Marshal cannot fail on it.
		panic(err)
	}
	return data
}

// bootstrapContentHash is a fixed content hash for the bootstrap hook's
// ManagedFile entries. It is never compared by ComputeDiff (the reserved name is
// excluded from diffing entirely, see ComputeDiff/Apply) — it only exists so the
// ManagedFile has a well-formed, non-empty ContentHash like every other kind.
var bootstrapContentHash = contentHashBytes(append(bootstrapHookJSON(), []byte(bootstrapScriptContent)...))

// EnsureBootstrapHook materializes and registers the cartographer-bootstrap hook
// (D60) for provider under baseDir, and returns lock with its ManagedFile entries
// refreshed (any previous bootstrap entries replaced — idempotent, safe to call on
// every `connect`/`sync`). Independent of any server manifest: this is what lets
// the hook install even when the server is unreachable at connect time, and what
// lets a later session self-heal once it comes back.
//
// kiro has no hook mechanism (destDir("hook", _, kiro) == ""): no-op, lock
// returned unchanged.
//
// dryRun performs no I/O and simulates the resulting paths (mirrors Apply's own
// DryRun contract) — used by `connect --dry-run`/`sync --dry-run`.
//
// The returned Lock is meant to be persisted by the caller (merged into the v2
// LockFile) — from then on PruneManaged/`cartographer disconnect` remove the
// bootstrap hook's files and provider-native registration exactly like any
// KB-provided hook, no new removal code needed (see ComputeDiff/Apply for how the
// reserved name is protected from being flagged as a server-driven orphan in the
// meantime).
func EnsureBootstrapHook(baseDir string, provider configurator.Provider, lock Lock, dryRun bool) (Lock, error) {
	destRel := destDir("hook", BootstrapHookName, provider)
	if destRel == "" {
		return lock, nil
	}

	var relPaths []string
	if dryRun {
		relPaths = []string{
			filepath.Join(destRel, "hook.json"),
			filepath.Join(destRel, bootstrapScriptName),
		}
		if provider == configurator.ProviderOpenCode {
			relPaths = append(relPaths, openCodePluginRelPath(BootstrapHookName))
		}
	} else {
		fullDestDir := filepath.Join(baseDir, destRel)
		if err := os.MkdirAll(fullDestDir, 0o755); err != nil {
			return Lock{}, fmt.Errorf("provisioning: mkdir %s: %w", fullDestDir, err)
		}
		hookJSONPath := filepath.Join(fullDestDir, "hook.json")
		if err := os.WriteFile(hookJSONPath, bootstrapHookJSON(), 0o644); err != nil {
			return Lock{}, fmt.Errorf("provisioning: write %s: %w", hookJSONPath, err)
		}
		scriptPath := filepath.Join(fullDestDir, bootstrapScriptName)
		if err := os.WriteFile(scriptPath, []byte(bootstrapScriptContent), 0o755); err != nil {
			return Lock{}, fmt.Errorf("provisioning: write %s: %w", scriptPath, err)
		}
		// WriteFile applies the mode only on creation: a pre-existing
		// bootstrap.sh (e.g. written 0600 by an earlier version) would stay
		// non-executable → Permission denied on every SessionStart.
		if err := os.Chmod(scriptPath, 0o755); err != nil {
			return Lock{}, fmt.Errorf("provisioning: chmod %s: %w", scriptPath, err)
		}
		relPaths = []string{
			filepath.Join(destRel, "hook.json"),
			filepath.Join(destRel, bootstrapScriptName),
		}

		// Register in the provider's native mechanism, reusing exactly the
		// D57/D58/D59 primitives — the very same code Apply uses for KB
		// hooks, with the hook.json just written above acting as the bridge.
		switch provider {
		case configurator.ProviderClaudeCode:
			if err := registerHookSettings(baseDir, BootstrapHookName, fullDestDir); err != nil {
				return Lock{}, fmt.Errorf("provisioning: register bootstrap hook in settings.json: %w", err)
			}
		case configurator.ProviderCodex:
			if err := registerHookConfigTOML(baseDir, BootstrapHookName, fullDestDir); err != nil {
				return Lock{}, fmt.Errorf("provisioning: register bootstrap hook in config.toml: %w", err)
			}
		case configurator.ProviderOpenCode:
			// openCodePluginRelPath prefixes with "cartographer-" unconditionally
			// (same helper every KB hook uses) — for BootstrapHookName
			// ("cartographer-bootstrap") that yields a double-prefixed file name
			// (cartographer-cartographer-bootstrap.js). Documented, deliberate
			// (D60): reusing the shared helper verbatim keeps registration and
			// removal (removeOpenCodePlugin, driven by PruneManaged/mf.Name) on
			// the exact same path-derivation logic, with zero risk of the two
			// drifting apart — a cosmetic double-prefix is a small price for
			// that guarantee.
			pluginRel, warning, err := registerOpenCodePlugin(baseDir, BootstrapHookName, fullDestDir)
			if err != nil {
				return Lock{}, fmt.Errorf("provisioning: register bootstrap hook as opencode plugin: %w", err)
			}
			if warning != "" {
				// SessionStart is always mapped (openCodeHookEvents) — a warning
				// here would mean the mapping regressed; treat as a hard error
				// rather than silently leaving the bootstrap hook unregistered.
				return Lock{}, fmt.Errorf("provisioning: bootstrap hook: %s", warning)
			}
			if pluginRel != "" {
				relPaths = append(relPaths, pluginRel)
			}
		}
	}

	managed := make([]ManagedFile, 0, len(relPaths))
	for _, rp := range relPaths {
		managed = append(managed, ManagedFile{
			Kind:        "hook",
			Name:        BootstrapHookName,
			Path:        rp,
			ContentHash: bootstrapContentHash,
		})
	}

	newManaged := make([]ManagedFile, 0, len(lock.Managed)+len(managed))
	for _, mf := range lock.Managed {
		if mf.Kind == "hook" && mf.Name == BootstrapHookName {
			continue
		}
		newManaged = append(newManaged, mf)
	}
	lock.Managed = append(newManaged, managed...)
	return lock, nil
}
