//go:build windows

package provisioning

// The Windows half of the bootstrap script (D60). Before this, the only script
// generated was `#!/bin/sh`, written 0o755 and then chmod-ed — three operations
// that on NTFS mean nothing — so layer 1 of D60 was dead on Windows without a
// single error to say so.

// bootstrapScriptName is the generated script's file name inside the hook's
// destination directory (destDir("hook", BootstrapHookName, provider)).
// `.cmd` rather than `.bat`: both are batch, `.cmd` is the modern spelling and
// is on the default PATHEXT.
const bootstrapScriptName = "bootstrap.cmd"

// bootstrapScriptContent is the batch equivalent of the POSIX script, with the
// same three guarantees: a silent sync (every stream discarded), always exit 0
// (a sync failure must never break session startup), and an immediate exit
// when `cartographer` is not resolvable — `where` is the batch `command -v`.
// As on POSIX, `update notice` keeps its stdout, which is empty unless a newer
// release exists (D254).
//
// CRLF line endings, and ASCII only: a batch file is read by cmd.exe, not by a
// POSIX shell, and neither its line-ending tolerance nor its code page is worth
// betting a silent session-start failure on. There is no executable bit to set
// (internal/execbit): being executable here is the extension's job, which is why
// this file is named .cmd and the POSIX one is not.
const bootstrapScriptContent = "@echo off\r\n" +
	"REM cartographer-bootstrap - generated by Cartographer (WP4/D60), do not edit.\r\n" +
	"where cartographer >nul 2>&1 || exit /b 0\r\n" +
	"cartographer sync --auto-trust >nul 2>&1\r\n" +
	"cartographer update notice 2>nul\r\n" +
	"exit /b 0\r\n"
