package provisioning

// Hermes delivery (D141). Hermes owns its own skills: a curator under
// HERMES_HOME/skills/ archives, rewrites and pins them from its own learning
// loop. Materializing there would put Cartographer and the curator in a
// permanent fight, so a KB skill is DELIVERED to skill-inbox/<name>/cartographer/
// as a proposal, with a generated SOURCE.md saying where it came from and what
// adopting it means. The agent decides; Cartographer never installs.

import (
	"fmt"
	"strings"

	"github.com/BeppeTemp/cartographer/internal/configurator"
)

// generatedArtifactFiles returns the files Cartographer adds to an artifact's
// materialized directory beyond the KB's own: hermes' SOURCE.md for a skill
// delivered to its inbox, and SOURCE.env (D316) for a KB skill materialized
// anywhere else.
//
// A KB skill that already ships a file with a generated name is a collision:
// overwriting it would silently destroy KB content, and delivering both is
// impossible. That one artifact fails with a warning naming it; the rest of
// the sync completes, and the collision persists (nothing is recorded in the
// lockfile) until the KB is fixed.
func generatedArtifactFiles(a Artifact, opts ApplyOptions, files []ArtifactFile) (generated []ArtifactFile, warning string, ok bool) {
	if a.Kind != "skill" {
		return nil, "", true
	}
	// Only the global cell is an inbox. A workspace skill (D364) is written to
	// .hermes/skills like any other client's, and a "proposal, nothing is
	// active" note there would be false.
	if opts.Provider == configurator.ProviderHermes && opts.Scope != ScopeProject {
		generated = []ArtifactFile{{Path: hermesSourceFile, Content: hermesSourceDoc(a)}}
	} else if kbName, fromKB := kbSourceName(a); fromKB {
		generated = []ArtifactFile{{Path: skillSourceEnvFile, Content: skillSourceEnv(kbName, opts.KBRoots[kbName])}}
	}
	for _, g := range generated {
		for _, f := range files {
			if strings.EqualFold(strings.TrimPrefix(f.Path, "./"), g.Path) {
				where := "the hermes inbox, which generates that file"
				if g.Path == skillSourceEnvFile {
					where = "this client: Cartographer generates that file"
				}
				return nil, fmt.Sprintf("skill %q ships its own %s: not delivered to %s (rename it in the KB)", a.Name, g.Path, where), false
			}
		}
	}
	return generated, "", true
}

// skillSourceEnvFile is written next to a materialized KB skill's SKILL.md so
// a script the skill ships can find its KB without parsing local config
// (D316). It exists only in the client directory, never in the KB: the values
// are this deployment's, not content.
const skillSourceEnvFile = "SOURCE.env"

// skillSourceEnv renders SOURCE.env: KEY=VALUE lines a script can `source` or
// grep. CARTOGRAPHER_KB_ROOT is written only when the KB's root is on this
// machine (a local deployment, or the server's own sync_apply): a client fed
// over HTTP has no local copy of the KB, and a server path would point at
// nothing. Values are not shell-quoted; a consumer that may meet a path with
// spaces quotes it. Deterministic, so an unchanged skill re-materializes
// byte-identically.
func skillSourceEnv(kbName, kbRoot string) []byte {
	var sb strings.Builder
	sb.WriteString("# Generated by Cartographer at sync: the KB this skill came from.\n")
	fmt.Fprintf(&sb, "CARTOGRAPHER_KB_NAME=%s\n", kbName)
	if kbRoot != "" && !strings.ContainsAny(kbRoot, "\n\r") {
		fmt.Fprintf(&sb, "CARTOGRAPHER_KB_ROOT=%s\n", kbRoot)
	}
	return []byte(sb.String())
}

// hermesSourceDoc renders the delivery note. Deterministic — no timestamp, no
// manifest revision — so an unchanged skill re-delivers byte-identically and
// the sync stays idempotent; the artifact's content hash is what distinguishes
// a new proposal from a re-delivery.
func hermesSourceDoc(a Artifact) []byte {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# Cartographer delivery: %s\n\n", a.Name)
	sb.WriteString("This directory was delivered by Cartographer. It is a **proposal**, not an installed skill:\n")
	sb.WriteString("nothing under `$HERMES_HOME/skills/` was written, and nothing here is active.\n\n")

	kb, fromKB := kbSourceName(a)
	if fromKB {
		fmt.Fprintf(&sb, "- Source: KB %q, path `%s`\n", kb, artifactSourcePath(a))
	} else {
		sb.WriteString("- Source: bundled with the Cartographer server\n")
	}
	fmt.Fprintf(&sb, "- Artifact content hash: `%s`\n\n", a.ContentHash)

	sb.WriteString("Adopting it is `skill_manage`'s job: compare it with the skill you already have, take what is\n")
	sb.WriteString("worth taking, then reload and verify. Cartographer re-delivers this directory in place on every\n")
	sb.WriteString("sync — the content hash above is what tells an unchanged re-delivery from a new proposal.\n\n")

	if fromKB {
		fmt.Fprintf(&sb, "To change this skill for every client, change it in the KB: `artifact_write` on KB %q, path\n`%s`. Edits made here reach nothing else and are replaced on the next sync.\n",
			kb, artifactSourcePath(a))
	} else {
		sb.WriteString("This skill ships inside the Cartographer binary: changing it for every client means changing\n")
		sb.WriteString("the release. Edits made here reach nothing else and are replaced on the next sync.\n")
	}
	return []byte(sb.String())
}
