package provisioning

const peerHookScriptName = "peers.cmd"

func peerHookScript(provider, event string) string {
	return "@echo off\r\n" +
		"REM cartographer peers hook (D341) - generated by Cartographer, do not edit.\r\n" +
		"where cartographer >nul 2>&1 || exit /b 0\r\n" +
		"cartographer peer hook " + provider + " " + event + "\r\n" +
		"exit /b 0\r\n"
}
