//go:build !windows

package provisioning

// peerHookScriptName is the generated script inside each peer hook's
// destination directory.
const peerHookScriptName = "peers.sh"

// peerHookScript is the body of a peer hook: it hands the hook's stdin to
// `cartographer peer hook`, which always exits 0 — a messaging failure must
// never break or stall a session.
func peerHookScript(provider, event string) string {
	return "#!/bin/sh\n" +
		"# cartographer peers hook (D341) — generated by Cartographer, do not edit.\n" +
		"command -v cartographer >/dev/null 2>&1 || exit 0\n" +
		"exec cartographer peer hook " + provider + " " + event + "\n"
}
