//go:build !windows

package provisioning

// The POSIX half of the write-findings script (D353); build-tagged like
// bootstrapscript_unix.go.

const writeFindingsScriptName = "write-findings.sh"

// writeFindingsScriptContent is a shim: stdin (the hook payload) reaches the
// subcommand, which owns every decision; the arguments (the per-provider
// feedback channel, D361) are forwarded. Only its exit 2 (feedback) is
// propagated; any other outcome, a crash included, becomes exit 0, because a
// hook must never break a session. Silent when cartographer is not on PATH.
const writeFindingsScriptContent = `#!/bin/sh
# cartographer-write-findings — generated by Cartographer (D353), do not edit.
command -v cartographer >/dev/null 2>&1 || exit 0
cartographer hook write-findings "$@"
[ "$?" -eq 2 ] && exit 2
exit 0
`
