//go:build windows

package provisioning

// The Windows half of the write-findings script (D353); CRLF and ASCII only,
// like bootstrapscript_windows.go.

const writeFindingsScriptName = "write-findings.cmd"

const writeFindingsScriptContent = "@echo off\r\n" +
	"REM cartographer-write-findings - generated by Cartographer (D353), do not edit.\r\n" +
	"where cartographer >nul 2>&1 || exit /b 0\r\n" +
	"cartographer hook write-findings %*\r\n" +
	"if %errorlevel% equ 2 exit /b 2\r\n" +
	"exit /b 0\r\n"
