// Package service manages the cartographer MCP server as a native per-user
// service: a launchd agent on macOS, a systemd user unit on Linux. It
// replaces local Docker deployment (docs/decisions/deployment-release.md D73).
//
// The package separates pure file generation (Render*, DefaultServerYAML,
// the path functions) from platform command execution (Manager, which runs
// launchctl/systemctl through an injectable runner) so the generation half
// is trivially unit-testable and the execution half is testable via a
// stubbed runner.
package service

import (
	"fmt"
	"path/filepath"
	"strings"
)

// packageManagerPrefixes are the directories a service's PATH must include
// beyond the platform default, in this order: the package managers that install
// the external binaries Cartographer shells out to (sops for secret
// resolution, git). Curated and fixed rather than copied from the installing
// user's shell, which would bake that user's whole environment into a service
// definition.
var packageManagerPrefixes = []string{"/opt/homebrew/bin", "/usr/local/bin", "/opt/local/bin"}

// platformDefaultPath is the minimal PATH a launchd job or a systemd user unit
// gets when the definition sets none.
var platformDefaultPath = []string{"/usr/bin", "/bin", "/usr/sbin", "/sbin"}

// servicePATH is the PATH written into the generated service definitions. A
// launchd job inherits a minimal PATH and a systemd user unit an equally short
// one, so a Homebrew-installed sops sits outside both and every secret
// resolution fails with "sops binary not found in PATH" — from the definition
// `service install` itself generated. The binary's own directory comes first:
// whatever installed Cartographer is the most likely place to hold its
// companions.
func servicePATH(binPath string) string {
	var dirs []string
	seen := map[string]bool{}
	add := func(d string) {
		if d == "" || d == "." || seen[d] {
			return
		}
		seen[d] = true
		dirs = append(dirs, d)
	}
	if binPath != "" {
		add(filepath.Dir(binPath))
	}
	for _, d := range packageManagerPrefixes {
		add(d)
	}
	for _, d := range platformDefaultPath {
		add(d)
	}
	return strings.Join(dirs, ":")
}

// RenderLaunchdPlist renders the launchd agent plist that runs
// `<binPath> serve --config <configPath>`, logging stdout/stderr to logPath.
func RenderLaunchdPlist(binPath, configPath, logPath string) string {
	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.cartographer.serve</string>
	<key>ProgramArguments</key>
	<array>
		<string>%s</string>
		<string>serve</string>
		<string>--config</string>
		<string>%s</string>
	</array>
	<key>EnvironmentVariables</key>
	<dict>
		<key>PATH</key>
		<string>%s</string>
	</dict>
	<key>RunAtLoad</key>
	<true/>
	<key>KeepAlive</key>
	<true/>
	<key>StandardOutPath</key>
	<string>%s</string>
	<key>StandardErrorPath</key>
	<string>%s</string>
</dict>
</plist>
`, binPath, configPath, servicePATH(binPath), logPath, logPath)
}

// RenderSystemdUnit renders the systemd user unit that runs
// `<binPath> serve --config <configPath>`, restarting on failure. Logs go to
// journald (the systemd default), no explicit log path. PATH is set from the
// same servicePATH the launchd plist uses, so the two definitions cannot drift.
func RenderSystemdUnit(binPath, configPath string) string {
	return fmt.Sprintf(`[Unit]
Description=Cartographer MCP server

[Service]
Environment=PATH=%s
ExecStart=%s serve --config %s
Restart=on-failure

[Install]
WantedBy=default.target
`, servicePATH(binPath), binPath, configPath)
}

// DefaultServerYAML renders the minimal `cartographer serve --config` YAML
// generated by `cartographer service install` when no config file exists yet
// at the target path. See config.example.yaml for the full set of options.
func DefaultServerYAML(dataDir, httpAddr string) string {
	return fmt.Sprintf(`# Generated by "cartographer service install".
# See config.example.yaml (repo root) for the full set of options.
http: %q
data: %q
init: true
# Set both values to a forge account when remote push rules validate authors.
# See config.example.yaml for identity and other git options.
git:
  # author_name: "Your Name"
  # author_email: "you@example.com"
`, httpAddr, dataDir)
}
