// Package service manages the cartographer MCP server as a native per-user
// service: a launchd agent on macOS, a systemd user unit on Linux. It
// replaces the local Docker-based deployment (see decisions.md).
//
// The package separates pure file generation (Render*, DefaultServerYAML,
// the path functions) from platform command execution (Manager, which runs
// launchctl/systemctl through an injectable runner) so the generation half
// is trivially unit-testable and the execution half is testable via a
// stubbed runner.
package service

import "fmt"

// RenderLaunchdPlist renders the launchd agent plist that runs
// `<binPath> serve --config <configPath>`, logging stdout/stderr to logPath.
func RenderLaunchdPlist(binPath, configPath, logPath string) string {
	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.cartographer.serve</string>
	<key>ProgramArguments</key>
	<array>
		<string>%s</string>
		<string>serve</string>
		<string>--config</string>
		<string>%s</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>KeepAlive</key>
	<true/>
	<key>StandardOutPath</key>
	<string>%s</string>
	<key>StandardErrorPath</key>
	<string>%s</string>
</dict>
</plist>
`, binPath, configPath, logPath, logPath)
}

// RenderSystemdUnit renders the systemd user unit that runs
// `<binPath> serve --config <configPath>`, restarting on failure. Logs go to
// journald (the systemd default), no explicit log path.
func RenderSystemdUnit(binPath, configPath string) string {
	return fmt.Sprintf(`[Unit]
Description=Cartographer MCP server

[Service]
ExecStart=%s serve --config %s
Restart=on-failure

[Install]
WantedBy=default.target
`, binPath, configPath)
}

// DefaultServerYAML renders the minimal `cartographer serve --config` YAML
// generated by `cartographer service install` when no config file exists yet
// at the target path. See config.example.yaml for the full set of options.
func DefaultServerYAML(dataDir, httpAddr string) string {
	return fmt.Sprintf(`# Generated by "cartographer service install".
# See config.example.yaml (repo root) for the full set of options.
http: %q
data: %q
init: true
`, httpAddr, dataDir)
}
