package kb

import (
	"path"
	"strings"
)

// JunkPatterns are the files an editor, an OS or an interpreter leaves next to
// the ones a person meant to write (D316). They are one list on purpose: Init
// writes them into data/.gitignore, and lint reports a tracked match
// (junk_file, junk_asset) and keeps it out of orphan_asset — a subagent once
// followed orphan_asset's "cite it" advice literally and cited a .pyc. A
// pattern ending in "/" names a directory anywhere in the path; every other one
// is a glob on the file's base name.
var JunkPatterns = []string{".DS_Store", "__pycache__/", "*.pyc", "*.pyo", "*~", "*.swp", "Thumbs.db"}

// IsJunkPath reports whether the slash-separated relative path matches one of
// JunkPatterns.
func IsJunkPath(rel string) bool {
	segs := strings.Split(strings.ReplaceAll(rel, "\\", "/"), "/")
	base := segs[len(segs)-1]
	for _, p := range JunkPatterns {
		if dir, ok := strings.CutSuffix(p, "/"); ok {
			for _, s := range segs[:len(segs)-1] {
				if s == dir {
					return true
				}
			}
			continue
		}
		if ok, _ := path.Match(p, base); ok {
			return true
		}
	}
	return false
}

// dataGitignore is the data/.gitignore Init writes: the JunkPatterns, inside
// the concept root only. D62 removed the repository-root .gitignore and that
// stands; this one is content that travels with the KB, like data/index.md.
func dataGitignore() string {
	return "# Generated by Cartographer — common junk files.\n" + strings.Join(JunkPatterns, "\n") + "\n"
}
