// Package repodocs holds the deterministic checks that keep this repository
// navigable by a coding agent, plus the generator for the decision index.
//
// It exists because the four things it verifies all fail *silently*. A context
// file over Codex's project_doc_max_bytes is not truncated with an error: the
// deepest instructions simply stop existing. A skill location that drifted from
// a symlink into a copy does not warn: two clients just start reading different
// procedures. A hand-maintained index does not complain when a decision is
// missing from it: it only stops being trustworthy, and then stops being read.
// A moved page does not report its inbound links.
//
// Everything here therefore runs inside `make test`, which CI already runs, so
// no one has to remember a separate command.
package repodocs

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// Budgets. These are not style preferences: each one is a limit a real client
// enforces, and the lowest of them is what the repository has to respect.
const (
	// Codex concatenates the AGENTS.md chain from the repository root down to
	// the working directory and stops adding files once the combined size
	// reaches project_doc_max_bytes, 32 KiB by default. What gets dropped is
	// the *deepest* file, i.e. the guidance closest to the code.
	MaxChainBytes = 32 * 1024

	// Antigravity documents a 12,000-character ceiling per rules file. It is
	// the lowest per-file limit among the four supported clients, so it is the
	// one that binds.
	MaxRootChars = 12000

	// Not a client limit but an adherence one: instruction-following degrades
	// as the file grows, and every client's guidance converges on "keep it
	// short". 120 lines is the pattern's own threshold.
	MaxRootLines = 120

	// Skill frontmatter, per Kiro's rules — the strictest of the four, so a
	// skill written to them is valid everywhere.
	MaxSkillNameChars        = 64
	MaxSkillDescriptionChars = 1024
)

// Markers for the generated block inside the hand-curated docs/decisions.md.
const (
	IndexBegin = "<!-- decisions:index:begin — generated by `make decisions-index`, do not edit by hand -->"
	IndexEnd   = "<!-- decisions:index:end -->"
)

// TopicOrder is the reading order of the topics in the generated index. A
// decision whose topic is not listed here fails the index test rather than
// being silently dropped: a new topic is a deliberate act.
var TopicOrder = []struct {
	Slug, Title string
}{
	{"architecture", "Cross-cutting architecture"},
	{"data-plane", "KB model and imports"},
	{"control-plane", "MCP tools, search and lint"},
	{"transport-auth", "HTTP, stdio and authorization"},
	{"concurrency-git", "Commits, synchronization and conflicts"},
	{"skills-services-secrets", "Skills, services and secrets"},
	{"sync-provisioning", "Provisioned artifacts"},
	{"client-configurator", "CLI, TUI and providers"},
	{"deployment-release", "Configuration, deployment and releases"},
	{"project-governance", "Repository and documentation policy"},
}

// SupportedClients are the agent clients this repository is developed with.
// Each one needs its own skill directory; .agents/skills is the only copy with
// real content and the others are symlinks into it.
var SupportedClients = []struct {
	Name, SkillDir string
}{
	{"Claude Code", ".claude/skills"},
	{"Kiro", ".kiro/skills"},
	// Codex and Antigravity read .agents/skills directly: no bridge needed.
}

// Decision is one record: exactly one file under docs/decisions.
type Decision struct {
	Num   int // 0 for the historical AD block, which has no single number
	Title string
	Topic string
	File  string // base name, e.g. "D115-mcp-allow-list.md"
}

var (
	decisionFile = regexp.MustCompile(`^D(\d+)-[a-z0-9-]+\.md$`)
	decisionH1   = regexp.MustCompile(`^# (D\d+ — .+|AD.+)$`)
	topicField   = regexp.MustCompile(`(?m)^topic:\s*(\S+)\s*$`)
)

// Root returns the repository root by walking up from the working directory
// until it finds go.mod, so the tests do not depend on where they are run from.
func Root() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("repodocs: no go.mod found above %s", dir)
		}
		dir = parent
	}
}

// LoadDecisions reads every decision file under docs/decisions, in numeric
// order, with the historical AD block first.
func LoadDecisions(root string) ([]Decision, error) {
	dir := filepath.Join(root, "docs", "decisions")
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var out []Decision
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".md") || name == "TEMPLATE.md" {
			continue
		}

		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return nil, err
		}
		text := string(data)

		d := Decision{File: name}

		m := topicField.FindStringSubmatch(text)
		if m == nil {
			return nil, fmt.Errorf("%s: missing `topic:` in frontmatter", name)
		}
		d.Topic = m[1]

		title, err := headingOf(text)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		d.Title = title

		if fm := decisionFile.FindStringSubmatch(name); fm != nil {
			n, err := strconv.Atoi(fm[1])
			if err != nil {
				return nil, fmt.Errorf("%s: %w", name, err)
			}
			d.Num = n
			if want := fmt.Sprintf("D%d — ", n); !strings.HasPrefix(title, want) {
				return nil, fmt.Errorf("%s: heading %q does not start with %q", name, title, want)
			}
		} else if !strings.HasPrefix(name, "AD") {
			return nil, fmt.Errorf("%s: name is neither D<n>-<slug>.md nor AD*.md", name)
		}

		out = append(out, d)
	}

	sort.Slice(out, func(i, j int) bool { return out[i].Num < out[j].Num })
	return out, nil
}

func headingOf(text string) (string, error) {
	sc := bufio.NewScanner(strings.NewReader(text))
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		if m := decisionH1.FindStringSubmatch(line); m != nil {
			return m[1], nil
		}
		if strings.HasPrefix(line, "# ") {
			return "", fmt.Errorf("first heading %q is not `# D<n> — title`", line)
		}
	}
	if err := sc.Err(); err != nil {
		return "", err
	}
	return "", fmt.Errorf("no `# ` heading found")
}

// RenderIndex builds the generated block for docs/decisions.md: one flat list
// per topic, no second level of routing. Explicit HTML anchors, so the
// per-topic links work identically on GitHub and on the mkdocs site.
func RenderIndex(decisions []Decision) string {
	byTopic := map[string][]Decision{}
	for _, d := range decisions {
		byTopic[d.Topic] = append(byTopic[d.Topic], d)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "## All decisions\n\n")
	fmt.Fprintf(&b, "%d records, one file each, grouped by the topic they belong to.\n", len(decisions))
	b.WriteString("In code and in prose the reference is the bare `D<n>`, with no path: resolve it\n")
	b.WriteString("with `ls docs/decisions/D<n>-*`. Add one with `make decisions-new`, then\n")
	b.WriteString("regenerate this list with `make decisions-index`.\n")

	for _, t := range TopicOrder {
		ds := byTopic[t.Slug]
		if len(ds) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n<a id=%q></a>\n\n### %s\n\n", t.Slug, t.Title)
		for _, d := range ds {
			fmt.Fprintf(&b, "- [%s](decisions/%s)\n", d.Title, d.File)
		}
	}
	return b.String()
}

// UnknownTopics returns the topics that are used by a decision but missing from
// TopicOrder, so the index test can name them instead of dropping them.
func UnknownTopics(decisions []Decision) []string {
	known := map[string]bool{}
	for _, t := range TopicOrder {
		known[t.Slug] = true
	}
	seen := map[string]bool{}
	var out []string
	for _, d := range decisions {
		if !known[d.Topic] && !seen[d.Topic] {
			seen[d.Topic] = true
			out = append(out, d.Topic)
		}
	}
	sort.Strings(out)
	return out
}

// ChainBytes returns, for every directory holding an AGENTS.md (or an
// AGENTS.override.md), the size of the instruction chain Codex would build when
// launched there: root to that directory, at most one file per directory, with
// the override winning. The global ~/.codex/AGENTS.md is deliberately not
// counted — verified not to consume project_doc_max_bytes.
func ChainBytes(root string) (map[string]int, error) {
	dirs := map[string]bool{}
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if name := d.Name(); name == ".git" || name == ".worktrees" || name == "test" {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Name() == "AGENTS.md" || d.Name() == "AGENTS.override.md" {
			rel, err := filepath.Rel(root, filepath.Dir(path))
			if err != nil {
				return err
			}
			dirs[rel] = true
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	out := map[string]int{}
	for dir := range dirs {
		total := 0
		for d := dir; ; d = filepath.Dir(d) {
			for _, name := range []string{"AGENTS.override.md", "AGENTS.md"} {
				fi, err := os.Stat(filepath.Join(root, d, name))
				if err == nil {
					total += int(fi.Size())
					break // at most one file per directory
				}
			}
			if d == "." {
				break
			}
		}
		out[dir] = total
	}
	return out, nil
}

// Markers for the generated code map inside AGENTS.md.
const (
	CodeMapBegin = "<!-- codemap:begin — generated by `make codemap` from the package doc comments, do not edit by hand -->"
	CodeMapEnd   = "<!-- codemap:end -->"
)

// codeMapWidth is where a synopsis is cut. Wide enough for a useful line, narrow
// enough that 26 packages stay inside the AGENTS.md budget.
const codeMapWidth = 104

// Package is one row of the generated code map.
type Package struct {
	Path     string // import path with the module prefix stripped
	Synopsis string
}

// Packages returns the repository's own packages with the first sentence of each
// package doc comment, which is what `go list` exposes as .Doc.
//
// The map is generated rather than written because a hand-written directory
// listing is the part of a context file that goes stale first, and the evidence
// on natural-language summaries of code is that they answer behavioural
// questions badly — what they are actually good for is *localisation*, telling
// an agent which package to open. A synopsis pulled from the package's own doc
// comment serves that, cannot drift from the code, and is visible to `go doc`
// as well, so it is written where a Go developer already looks.
func Packages(root string) ([]Package, error) {
	cmd := exec.Command("go", "list", "-f",
		"{{.ImportPath}}\t{{.Doc}}", "./cmd/...", "./internal/...")
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list: %w", err)
	}

	const prefix = "github.com/BeppeTemp/cartographer/"
	var pkgs []Package
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		path, doc, ok := strings.Cut(line, "\t")
		if !ok {
			continue
		}
		pkgs = append(pkgs, Package{
			Path:     strings.TrimPrefix(path, prefix),
			Synopsis: shorten(doc),
		})
	}
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].Path < pkgs[j].Path })
	return pkgs, nil
}

// shorten reduces a package synopsis to one readable clause: it drops the
// conventional "Package <name> " opener, cuts at the first clause boundary, and
// hard-truncates on a word boundary.
func shorten(doc string) string {
	doc = strings.Join(strings.Fields(doc), " ")
	if doc == "" {
		return ""
	}
	if _, rest, ok := strings.Cut(doc, " "); ok && strings.HasPrefix(doc, "Package ") {
		if _, after, ok := strings.Cut(rest, " "); ok {
			doc = after
		}
	}
	doc = strings.TrimPrefix(doc, "— ")
	for _, sep := range []string{": ", "; ", " — "} {
		if i := strings.Index(doc, sep); i > 0 && i < codeMapWidth {
			doc = doc[:i]
			break
		}
	}
	if len(doc) > codeMapWidth {
		cut := doc[:codeMapWidth]
		if i := strings.LastIndexByte(cut, ' '); i > codeMapWidth/2 {
			cut = cut[:i]
		}
		doc = strings.TrimRight(cut, " ,.") + "…"
	}
	return strings.TrimRight(doc, ".")
}

// RenderCodeMap builds the generated block for AGENTS.md.
func RenderCodeMap(pkgs []Package) string {
	width := 0
	for _, p := range pkgs {
		if len(p.Path) > width {
			width = len(p.Path)
		}
	}

	var b strings.Builder
	b.WriteString("Generated from the package doc comments — `make codemap` after adding a package.\n")
	b.WriteString("The synopsis says which package to open; what it does is in `go doc <pkg>`.\n\n```\n")
	for _, p := range pkgs {
		fmt.Fprintf(&b, "%-*s  %s\n", width, p.Path, p.Synopsis)
	}
	b.WriteString("```\n")
	return b.String()
}

// CitedDecisions returns every decision number referenced from Go source and from
// the AGENTS.md files, with one example location each, so a reference that no
// longer resolves can be named. The bare `D<n>` is the reference convention in
// this repository — no path, so a reworded title does not break it — and the only
// thing that keeps it honest is checking that the number exists.
//
// A number followed by "(retired)" or "(gap)" is skipped: that is how this
// repository names a number that deliberately has no record (D188 is retired,
// 163 is a gap — D206), and saying so must not be mistaken for claiming the
// record exists.
func CitedDecisions(root string) (map[int]string, error) {
	ref := regexp.MustCompile(`\bD([0-9]{1,3})\b(\s*\((?:retired|gap)\))?`)
	found := map[int]string{}

	record := func(path string) error {
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(root, path)
		for _, m := range ref.FindAllStringSubmatch(string(data), -1) {
			if m[2] != "" {
				continue // explicitly declared as having no record
			}
			n, err := strconv.Atoi(m[1])
			if err != nil {
				continue
			}
			if _, seen := found[n]; !seen {
				found[n] = rel
			}
		}
		return nil
	}

	for _, dir := range []string{"cmd", "internal"} {
		err := filepath.WalkDir(filepath.Join(root, dir), func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				return nil
			}
			// the bundled KB skills reference decisions of the KB they serve,
			// not of this repository
			if !strings.HasSuffix(path, ".go") && d.Name() != "AGENTS.md" {
				return nil
			}
			return record(path)
		})
		if err != nil {
			return nil, err
		}
	}
	if err := record(filepath.Join(root, "AGENTS.md")); err != nil {
		return nil, err
	}
	return found, nil
}

// KnownDanglingDecisions are references that do not resolve and are not fixed by
// guessing. Each one needs a reason and a way out, or the list becomes the place
// where the gate goes to die.
//
// Empty, and worth keeping empty: the first thing this check found was
// D163 (gap), cited eight times as an established decision with no record
// anywhere. It turned out not to be a missing record but a copied off-by-one —
// the trap those eight comments describe is D162 — and the fix was to renumber
// them, not to write the record. See D206.
var KnownDanglingDecisions = map[int]string{}
