// Package repodocs holds the deterministic checks that keep this repository
// navigable by a coding agent, plus the generators for the decision index and
// the code map.
//
// It exists because everything it verifies fails *silently*. A context file
// over Codex's project_doc_max_bytes is not truncated with an error: the
// deepest instructions simply stop existing. A skill whose frontmatter is not
// valid YAML is not reported: the client drops the skill and lists the others.
// A skill location that drifted from a symlink into a copy does not warn: two
// clients just start reading different procedures. A hand-maintained index does
// not complain when a decision is missing from it: it only stops being
// trustworthy, and then stops being read. A moved page does not report its
// inbound links, and a `D<n>` or a `docs/…` path in a comment is checked by
// nothing at all.
//
// Everything here therefore runs inside `make test`, which CI already runs, so
// no one has to remember a separate command.
package repodocs

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/BeppeTemp/cartographer/internal/configurator"
)

// Budgets. These are not style preferences: each one is a limit something real
// enforces, and the lowest of them is what the repository has to respect.
const (
	// MaxChainBytes is Codex's project_doc_max_bytes (32 KiB by default). Codex
	// concatenates the AGENTS.md chain from the repository root down to the
	// working directory and stops adding files once the combined size reaches
	// it. What gets dropped is the *deepest* file, i.e. the guidance closest to
	// the code.
	MaxChainBytes = 32 * 1024

	// MaxRootChars bounds the whole of AGENTS.md, generated blocks included,
	// because a client loads the whole file.
	//
	// No client this repository can verify publishes a per-file ceiling for a
	// project instruction file, so this is *our* ceiling, not a vendor's: 12.000
	// characters, chosen because instruction adherence degrades as the file
	// grows and because it keeps every AGENTS.md chain far inside MaxChainBytes
	// even with two nested files. Raising it is allowed and is deliberately a
	// visible edit to this constant (D207).
	MaxRootChars = 12000

	// MaxRootLines bounds the *hand-written* part of AGENTS.md — the file with
	// its generated blocks removed. Measuring the whole file would make "add a
	// Go package" fail a documentation test with a message telling the author to
	// move a prose section, which is the wrong instruction for that change: the
	// generated block is bounded by MaxRootChars and by the code map's own
	// column width instead (D209).
	MaxRootLines = 120

	// Skill frontmatter, per Kiro's rules — the strictest of the four clients,
	// so a skill written to them is valid everywhere.
	MaxSkillNameChars        = 64
	MaxSkillDescriptionChars = 1024
)

// Markers for the generated block inside the hand-curated docs/decisions.md.
const (
	IndexBegin = "<!-- decisions:index:begin — generated by `make decisions-index`, do not edit by hand -->"
	IndexEnd   = "<!-- decisions:index:end -->"
)

// Markers for the generated code map inside AGENTS.md.
const (
	CodeMapBegin = "<!-- codemap:begin — generated by `make codemap` from the package doc comments, do not edit by hand -->"
	CodeMapEnd   = "<!-- codemap:end -->"
)

// TopicOrder is the reading order of the topics in the generated index. A
// decision whose topic is not listed here fails the index test rather than
// being silently dropped: a new topic is a deliberate act.
var TopicOrder = []struct {
	Slug, Title string
}{
	{"architecture", "Cross-cutting architecture"},
	{"data-plane", "KB model and imports"},
	{"control-plane", "MCP tools, search and lint"},
	{"transport-auth", "HTTP, stdio and authorization"},
	{"concurrency-git", "Commits, synchronization and conflicts"},
	{"skills-services-secrets", "Skills, services and secrets"},
	{"sync-provisioning", "Provisioned artifacts"},
	{"client-configurator", "CLI, TUI and providers"},
	{"deployment-release", "Configuration, deployment and releases"},
	{"project-governance", "Repository and documentation policy"},
}

// CanonicalSkillDir is the one copy of each skill: the path Codex documents for
// repository-local skills, which is why it was chosen as the canonical one
// rather than a location of our own invention (D203).
const CanonicalSkillDir = ".agents/skills"

// ClientSurfaces is what CONTRIBUTING.md §Working with an agent client claims,
// as data, for the four clients this repository is developed with.
//
// It exists because that table was written from assumption once already and
// contradicted this repository's own audited provider matrix for a whole client:
// Antigravity was claimed to read `AGENTS.md` and `.agents/skills` natively and
// to take a project MCP config at `.agents/mcp_config.json`, while
// internal/provisioning/workspacescope.go records that its configuration root is
// global — ~/.gemini — with no project-local cell of any kind (D193, D207).
// TestClientSkillSurfacesMatchTheProviderRegistry checks each row against
// provisioning.ProjectDestination, so the prose cannot drift from the matrix
// again without failing.
//
// SkillDir is the repository-relative directory a skill of ours lands in for that
// client, empty when the client has no project-local skill scope at all.
// RowMustSay is a substring the client's row in CONTRIBUTING.md has to contain:
// for a client with no project-local scope it is the global location, so the row
// cannot say nothing and leave the reader to assume.
var ClientSurfaces = []struct {
	Provider   configurator.Provider
	Name       string
	SkillDir   string
	RowMustSay string
}{
	{configurator.ProviderCodex, "Codex", CanonicalSkillDir, CanonicalSkillDir},
	{configurator.ProviderKiro, "Kiro", ".kiro/skills", ".kiro/skills"},
	{configurator.ProviderClaudeCode, "Claude Code", ".claude/skills", ".claude/skills"},
	{configurator.ProviderAntigravity, "Antigravity", "", "~/.gemini/config/skills"},
}

// SupportedClients are the clients that need a *bridge* to reach the canonical
// copy of each skill: they have a project-local skill directory and it is not
// CanonicalSkillDir. Derived from ClientSurfaces, and checked against it, so the
// symlink gate covers exactly the clients that need one.
func SupportedClients() []struct{ Name, SkillDir string } {
	var out []struct{ Name, SkillDir string }
	for _, c := range ClientSurfaces {
		if c.SkillDir == "" || c.SkillDir == CanonicalSkillDir {
			continue
		}
		out = append(out, struct{ Name, SkillDir string }{c.Name, c.SkillDir})
	}
	return out
}

// GapDecisions are numbers that deliberately have no record and must never be
// reused. A citation of one resolves; a *file* claiming one fails the test,
// which is how "must not be reused" stops being a comment and becomes a gate.
//
// Both halves matter. Without the first, a reference that was always meant to
// point at nothing fails forever; without the second, the number silently comes
// back attached to a different decision, and released CHANGELOG entries and git
// history that discussed the old meaning start reading as a description of the
// new one (D206, D188).
var GapDecisions = map[int]string{
	4:   "never filed; nothing references it",
	6:   "never filed; nothing references it",
	7:   "never filed; nothing references it",
	11:  "never filed; nothing references it",
	163: "a copied off-by-one for D162, not a missing record — see D206",
}

// ReservedDecisions are numbers held by an open plan issue whose record arrives
// with the implementation. A plan title reserves its number before any file
// exists (CONTRIBUTING.md §Plan issues), so a forward reference to one is
// correct, not dangling — and this is where that is declared instead of being
// indistinguishable from a mistake.
//
// An entry is removed when the plan lands and writes its record: a reserved
// number that already has a file fails the test. A plan abandoned without
// implementing gets a "retired" record of its own (D130) or moves to
// GapDecisions — it does not stay here.
var ReservedDecisions = map[int]string{}

// Decision is one record: exactly one file under docs/decisions.
type Decision struct {
	Num   int // 0 for the historical AD block, which has no single number
	Title string
	Topic string
	File  string // base name, e.g. "D115-mcp-allow-list.md"
}

var (
	decisionFile = regexp.MustCompile(`^D(\d+)-[a-z0-9-]+\.md$`)
	decisionH1   = regexp.MustCompile(`^# (D\d+ — .+|AD.+)$`)
	topicField   = regexp.MustCompile(`(?m)^topic:\s*(\S.*?)\s*$`)
)

// Root returns the repository root by walking up from the working directory
// until it finds go.mod, so the tests do not depend on where they are run from.
func Root() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("repodocs: no go.mod found above %s", dir)
		}
		dir = parent
	}
}

// LoadDecisions reads every decision file under docs/decisions, in numeric
// order, with the historical AD block first.
func LoadDecisions(root string) ([]Decision, error) {
	dir := filepath.Join(root, "docs", "decisions")
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var out []Decision
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".md") || name == "TEMPLATE.md" {
			continue
		}

		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return nil, err
		}
		text := string(data)

		d := Decision{File: name}

		m := topicField.FindStringSubmatch(text)
		if m == nil {
			return nil, fmt.Errorf("%s: missing `topic:` in frontmatter", name)
		}
		d.Topic = m[1]

		title, err := headingOf(text)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		d.Title = title

		if fm := decisionFile.FindStringSubmatch(name); fm != nil {
			n, err := strconv.Atoi(fm[1])
			if err != nil {
				return nil, fmt.Errorf("%s: %w", name, err)
			}
			d.Num = n
			if want := fmt.Sprintf("D%d — ", n); !strings.HasPrefix(title, want) {
				return nil, fmt.Errorf("%s: heading %q does not start with %q", name, title, want)
			}
		} else if !strings.HasPrefix(name, "AD") {
			return nil, fmt.Errorf("%s: name is neither D<n>-<slug>.md nor AD*.md", name)
		}

		out = append(out, d)
	}

	sort.Slice(out, func(i, j int) bool {
		if out[i].Num != out[j].Num {
			return out[i].Num < out[j].Num
		}
		return out[i].File < out[j].File
	})
	return out, nil
}

func headingOf(text string) (string, error) {
	sc := bufio.NewScanner(strings.NewReader(text))
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		if m := decisionH1.FindStringSubmatch(line); m != nil {
			return m[1], nil
		}
		if strings.HasPrefix(line, "# ") {
			return "", fmt.Errorf("first heading %q is not `# D<n> — title`", line)
		}
	}
	if err := sc.Err(); err != nil {
		return "", err
	}
	return "", fmt.Errorf("no `# ` heading found")
}

// TemplatePlaceholders are strings that only `docs/decisions/TEMPLATE.md` and a
// freshly created, unwritten decision contain. `make decisions-new` fills in the
// number and leaves the rest: without this check the half-written file is indexed
// as "D<n> — <title>", and `<title>` renders as an HTML tag, so the index entry
// appears blank on GitHub and on the published site (D209).
var TemplatePlaceholders = []string{
	"<one of the topics in internal/repodocs.TopicOrder>",
	"<one line: the choice, not the problem>",
	"— <title>",
}

// RenderIndex builds the generated block for docs/decisions.md: one flat list
// per topic, no second level of routing. Explicit HTML anchors, so the
// per-topic links work identically on GitHub and on the mkdocs site.
func RenderIndex(decisions []Decision) string {
	byTopic := map[string][]Decision{}
	for _, d := range decisions {
		byTopic[d.Topic] = append(byTopic[d.Topic], d)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "## All decisions\n\n")
	fmt.Fprintf(&b, "%d records, one file each, grouped by the topic they belong to.\n", len(decisions))
	b.WriteString("In code and in prose the reference is the bare `D<n>`, with no path: resolve it\n")
	b.WriteString("with `ls docs/decisions/D<n>-*`. Add one with `make decisions-new`, then\n")
	b.WriteString("regenerate this list with `make decisions-index`.\n")

	for _, t := range TopicOrder {
		ds := byTopic[t.Slug]
		if len(ds) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n<a id=%q></a>\n\n### %s\n\n", t.Slug, t.Title)
		for _, d := range ds {
			fmt.Fprintf(&b, "- [%s](decisions/%s)\n", d.Title, d.File)
		}
	}
	return b.String()
}

// UnknownTopics returns the topics that are used by a decision but missing from
// TopicOrder, so the index test can name them instead of dropping them.
func UnknownTopics(decisions []Decision) []string {
	known := map[string]bool{}
	for _, t := range TopicOrder {
		known[t.Slug] = true
	}
	seen := map[string]bool{}
	var out []string
	for _, d := range decisions {
		if !known[d.Topic] && !seen[d.Topic] {
			seen[d.Topic] = true
			out = append(out, d.Topic)
		}
	}
	sort.Strings(out)
	return out
}

// ChainBytes returns, for every directory holding an AGENTS.md (or an
// AGENTS.override.md), the size of the instruction chain Codex would build when
// launched there: root to that directory, at most one file per directory, with
// the override winning. The global ~/.codex/AGENTS.md is deliberately not
// counted — verified not to consume project_doc_max_bytes.
//
// test/e2e/fixtures is skipped because a fixture KB carries its own AGENTS.md as
// *content under test*: it is never part of this repository's instruction chain,
// and counting it would measure the wrong thing.
func ChainBytes(root string) (map[string]int, error) {
	dirs, err := InstructionDirs(root)
	if err != nil {
		return nil, err
	}

	out := map[string]int{}
	for _, dir := range dirs {
		total := 0
		for d := dir; ; d = filepath.Dir(d) {
			for _, name := range []string{"AGENTS.override.md", "AGENTS.md"} {
				fi, err := os.Stat(filepath.Join(root, d, name))
				if err == nil {
					total += int(fi.Size())
					break // at most one file per directory
				}
			}
			if d == "." {
				break
			}
		}
		out[dir] = total
	}
	return out, nil
}

// InstructionDirs returns, sorted and relative to root, every directory holding
// an AGENTS.md or an AGENTS.override.md, with the same exclusions as the
// reference gates (skipDir).
func InstructionDirs(root string) ([]string, error) {
	seen := map[string]bool{}
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		if d.IsDir() {
			if skipDir(rel, d.Name()) {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Name() == "AGENTS.md" || d.Name() == "AGENTS.override.md" {
			seen[filepath.Dir(rel)] = true
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	dirs := make([]string, 0, len(seen))
	for dir := range seen {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)
	return dirs, nil
}

// referenceFileExts are the file types whose text can carry a reference this
// package checks: code and shell comments, prose, and the two YAML files that
// cite decisions in their comments (.goreleaser.yaml, config.example.yaml).
var referenceFileExts = map[string]bool{
	".go": true, ".md": true, ".sh": true, ".yaml": true, ".yml": true,
}

// skipDir reports whether a directory is outside every reference gate's corpus.
// Named explicitly rather than derived from .gitignore: build output and vendored
// state carry no references, and a fixture KB's references belong to that
// fixture, not to this repository.
func skipDir(rel, name string) bool {
	switch rel {
	case "test/e2e/fixtures", "test/install/fixtures":
		return true
	}
	switch name {
	case ".git", ".worktrees", ".vscode", "bin", "dist", "site", "node_modules",
		"demo-kb", "migrated-kb", "graphify-out":
		return true
	}
	return false
}

// skipFile reports whether a file is excluded from the reference gates.
// CHANGELOG.md is a released historical record: it legitimately names paths and
// decisions as they were at the time, and editing it to satisfy a gate would be
// falsifying it.
func skipFile(rel string) bool {
	return filepath.Base(rel) == "CHANGELOG.md"
}

// TextFiles walks the repository and returns, relative to root and sorted, every
// text file the reference gates read.
//
// It walks the filesystem rather than asking git, so a decision file that has
// been written but not yet staged is already in scope: a gate that passes
// locally and fails in CI is worse than no gate.
func TextFiles(root string) ([]string, error) {
	var out []string
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		if d.IsDir() {
			if rel != "." && skipDir(rel, d.Name()) {
				return filepath.SkipDir
			}
			return nil
		}
		if !d.Type().IsRegular() { // symlinked skill bridges point at files already in scope
			return nil
		}
		if !referenceFileExts[filepath.Ext(rel)] || skipFile(rel) {
			return nil
		}
		out = append(out, rel)
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(out)
	return out, nil
}

// MarkdownFiles is TextFiles restricted to markdown, the corpus of the link
// checks.
func MarkdownFiles(root string) ([]string, error) {
	files, err := TextFiles(root)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, f := range files {
		if filepath.Ext(f) == ".md" {
			out = append(out, f)
		}
	}
	return out, nil
}

// Packages returns the repository's own packages with the first sentence of each
// package doc comment, which is what `go list` exposes as .Doc.
//
// The map is generated rather than written because a hand-written directory
// listing is the part of a context file that goes stale first, and the evidence
// on natural-language summaries of code is that they answer behavioural
// questions badly — what they are actually good for is *localisation*, telling
// an agent which package to open. A synopsis pulled from the package's own doc
// comment serves that, cannot drift from the code, and is visible to `go doc`
// as well, so it is written where a Go developer already looks.
func Packages(root string) ([]Package, error) {
	cmd := exec.Command("go", "list", "-f",
		"{{.ImportPath}}\t{{.Doc}}", "./cmd/...", "./internal/...")
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list: %w", err)
	}

	const prefix = "github.com/BeppeTemp/cartographer/"
	var pkgs []Package
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		path, doc, ok := strings.Cut(line, "\t")
		if !ok {
			continue
		}
		pkgs = append(pkgs, Package{
			Path:     strings.TrimPrefix(path, prefix),
			Synopsis: shorten(doc),
		})
	}
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].Path < pkgs[j].Path })
	return pkgs, nil
}

// codeMapWidth is where a synopsis is cut. Wide enough for a useful line, narrow
// enough that the whole map stays inside the AGENTS.md character budget.
const codeMapWidth = 104

// Package is one row of the generated code map.
type Package struct {
	Path     string // import path with the module prefix stripped
	Synopsis string
}

// shorten reduces a package synopsis to one readable clause: it drops the
// conventional "Package <name> " opener, cuts at the first clause boundary, and
// hard-truncates on a word boundary.
func shorten(doc string) string {
	doc = strings.Join(strings.Fields(doc), " ")
	if doc == "" {
		return ""
	}
	if _, rest, ok := strings.Cut(doc, " "); ok && strings.HasPrefix(doc, "Package ") {
		if _, after, ok := strings.Cut(rest, " "); ok {
			doc = after
		}
	}
	doc = strings.TrimPrefix(doc, "— ")
	for _, sep := range []string{": ", "; ", " — "} {
		if i := strings.Index(doc, sep); i > 0 && i < codeMapWidth {
			doc = doc[:i]
			break
		}
	}
	if len(doc) > codeMapWidth {
		cut := doc[:codeMapWidth]
		if i := strings.LastIndexByte(cut, ' '); i > codeMapWidth/2 {
			cut = cut[:i]
		}
		doc = strings.TrimRight(cut, " ,.") + "…"
	}
	return strings.TrimRight(doc, ".")
}

// RenderCodeMap builds the generated block for AGENTS.md.
func RenderCodeMap(pkgs []Package) string {
	width := 0
	for _, p := range pkgs {
		if len(p.Path) > width {
			width = len(p.Path)
		}
	}

	var b strings.Builder
	b.WriteString("Generated from the package doc comments — `make codemap` after adding a package.\n")
	b.WriteString("The synopsis says which package to open; what it does is in `go doc <pkg>`.\n\n```\n")
	for _, p := range pkgs {
		fmt.Fprintf(&b, "%-*s  %s\n", width, p.Path, p.Synopsis)
	}
	b.WriteString("```\n")
	return b.String()
}

// BlockBody returns the text between begin and end, exclusive of the markers.
// It insists on exactly one of each, in order: a duplicated marker pair is how a
// generated block silently stops being the one that is checked.
func BlockBody(content, begin, end string) (string, error) {
	if n := strings.Count(content, begin); n != 1 {
		return "", fmt.Errorf("found %d begin markers, want exactly 1:\n  %s", n, begin)
	}
	if n := strings.Count(content, end); n != 1 {
		return "", fmt.Errorf("found %d end markers, want exactly 1:\n  %s", n, end)
	}
	i := strings.Index(content, begin) + len(begin)
	j := strings.Index(content, end)
	if j < i {
		return "", fmt.Errorf("the end marker precedes the begin marker")
	}
	return content[i:j], nil
}

// StripGeneratedBlocks removes every generated block this package owns, markers
// included, so a budget can be measured on the hand-written text alone.
func StripGeneratedBlocks(content string) string {
	for _, pair := range [][2]string{{CodeMapBegin, CodeMapEnd}, {IndexBegin, IndexEnd}} {
		i := strings.Index(content, pair[0])
		j := strings.Index(content, pair[1])
		if i < 0 || j < i {
			continue
		}
		content = content[:i] + content[j+len(pair[1]):]
	}
	return content
}

// decisionRef matches this repository's reference convention: the bare `D<n>`,
// no path, so a reworded title does not break it. Nothing about it is checked by
// the compiler, which is why CitedDecisions exists.
var decisionRef = regexp.MustCompile(`\bD([0-9]{1,3})\b`)

// CitedDecisions returns every decision number referenced from the corpus, with
// the files that reference it, so a reference that no longer resolves can be
// named at every site rather than one.
func CitedDecisions(root string) (map[int][]string, error) {
	files, err := TextFiles(root)
	if err != nil {
		return nil, err
	}

	found := map[int][]string{}
	for _, rel := range files {
		data, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			return nil, err
		}
		seen := map[int]bool{}
		for _, m := range decisionRef.FindAllStringSubmatch(string(data), -1) {
			n, err := strconv.Atoi(m[1])
			if err != nil || seen[n] {
				continue
			}
			seen[n] = true
			found[n] = append(found[n], rel)
		}
	}
	return found, nil
}

// docPathRef matches a repository-relative path into the documentation surface.
// The character class excludes `<` and `>`, so the placeholder forms this
// repository writes on purpose — `docs/decisions/D<n>-<slug>.md` — are not
// mistaken for pointers.
var docPathRef = regexp.MustCompile(`(?:docs|\.agents/skills)/[A-Za-z0-9._/-]+\.md`)

// CitedDocPaths returns every documentation path cited anywhere in the corpus,
// with the files citing it. Unlike the markdown-link check this reads *any* text,
// which is the only way to see the pointers that live in Go and shell comments —
// where a page rename leaves them dangling with nothing to report it.
func CitedDocPaths(root string) (map[string][]string, error) {
	files, err := TextFiles(root)
	if err != nil {
		return nil, err
	}

	found := map[string][]string{}
	for _, rel := range files {
		data, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			return nil, err
		}
		seen := map[string]bool{}
		for _, m := range docPathRef.FindAllString(string(data), -1) {
			if seen[m] {
				continue
			}
			seen[m] = true
			found[m] = append(found[m], rel)
		}
	}
	return found, nil
}

// SkillFrontmatter is the frontmatter of a SKILL.md, parsed by the same
// spec-compliant YAML parser a client uses.
type SkillFrontmatter struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
}

// ParseSkillFrontmatter reads a SKILL.md and parses its frontmatter with
// gopkg.in/yaml.v3.
//
// The parser is the point of this function. A hand-rolled "split on the first
// colon" reader accepts frontmatter that no client can load — an unquoted plain
// scalar containing ": " is a YAML syntax error, and the observed behaviour is
// that the client drops the skill and lists the others, with no message anywhere
// (D207). Cartographer's own OKF frontmatter reader is deliberately not used
// here either: it is lenient by design for KB concepts, and the question this
// asks is what a *client* will accept.
func ParseSkillFrontmatter(path string) (*SkillFrontmatter, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	text := string(data)
	if !strings.HasPrefix(text, "---\n") {
		return nil, fmt.Errorf("no YAML frontmatter: the file must start with a `---` line")
	}
	end := strings.Index(text[4:], "\n---")
	if end < 0 {
		return nil, fmt.Errorf("the YAML frontmatter is never closed by a `---` line")
	}

	var fm SkillFrontmatter
	if err := yaml.Unmarshal([]byte(text[4:4+end]), &fm); err != nil {
		return nil, fmt.Errorf("the frontmatter is not valid YAML, so a client will "+
			"skip this skill without reporting anything: %w\n"+
			"  the usual cause is an unquoted value containing \": \" — quote it, or "+
			"replace the colon with an em dash", err)
	}
	return &fm, nil
}
